// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('add OS (1)', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('add OS (1)', async function() {
    await driver.get("http://localhost/fernando2024/FranciscoEmbalagens/")
    await driver.manage().window().setRect({ width: 845, height: 1040 })
    await driver.findElement(By.id("adminCrud")).click()
    await driver.findElement(By.linkText("Ordem Serviço")).click()
    await driver.findElement(By.name("id_cli")).click()
    {
      const dropdown = await driver.findElement(By.name("id_cli"))
      await dropdown.findElement(By.xpath("//option[. = 'Rafael Souza']")).click()
    }
    await driver.findElement(By.css("button:nth-child(13)")).click()
    await driver.findElement(By.name("id_cli")).click()
    {
      const dropdown = await driver.findElement(By.name("id_cli"))
      await dropdown.findElement(By.xpath("//option[. = 'Pedro Santos']")).click()
    }
    await driver.findElement(By.css("button:nth-child(13)")).click()
    await driver.findElement(By.name("id_cli")).click()
    {
      const dropdown = await driver.findElement(By.name("id_cli"))
      await dropdown.findElement(By.xpath("//option[. = 'Maria Oliveira']")).click()
    }
    await driver.findElement(By.css("button:nth-child(13)")).click()
    await driver.findElement(By.name("id_cli")).click()
    {
      const dropdown = await driver.findElement(By.name("id_cli"))
      await dropdown.findElement(By.xpath("//option[. = 'Bruno Fernandes']")).click()
    }
    await driver.findElement(By.css("button:nth-child(13)")).click()
  })
})
